server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/safeguard?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: maheshkulkarni9797@gmail.com
    password: ohnv npdn yvlh jpwb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    cors:
      allowed-origins: "http://127.0.0.1:5500" # Allow the specific frontend origin
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*" # Allow all headers
      allow-credentials: true

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  pattern:
    file: "%d{yyyy-MM-dd } [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:/Users/shree/Desktop/application.log

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24 hours in milliseconds
